### ISSUE TITLE
Roadmap for 2.0

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/WP-Tests-Starter#10]
## Simplify bootstrapping/setup

Right now you have to define half a dozen constants (most of them DB credentials) in the phpunit.xml file just to work. I'd like to have a DB URL here like `mysql://user:password@host/db_name?table_prefix=wp_` as single, yet human readable configuration. It should be read by default from an environment variable.

Ideally we ship a default boostrap file with a common set up to ease the set up of tests with WP Tests Starter

## API Updates

* [x] Remove the `SaltGeneratorInterface` it's simply over the top
* [x] Reduce public methods of `WpTestsStarter`, there are simply to much of them that are not needed to be public
* [x] Rename namespace `Common` to `Helper`
* [x] Rename `WpTestsStarter::createDummyConfigFile()` to `::writeConfigFile()`
* [x] Constants and globals should not set immediately but first on `WpTestsStarter::bootstrap()`. Thus `::defineDbName()` should be renamed to `::useDbName()` and so on
* [x] Fluent interface for `WpTestsStarter` public methods
* [x] Add method `WpTestsStarter::addLivePlugin(callable $plugin)` to directly run on `muplugins_loaded`
* [x] Add methods `WpTestsStarter::addFilter()` and `::addAction()` to register listener before WP is loaded
* [ ] Improve serialization of constants that gets on-the-fly written in the config file
* [ ] Separate internals from `WpTestsStarter` into extra classes following single responsibility principle
* [ ] Add method `WpTestsStarter::useMuPluginDir(string $muPluginDir)`
* [ ] Add method `WpTestsStarter::addNetworkActivePlugin(string $plugin)` 
* [ ] Replace `wordpress/wordpress` repo with `roots/wordpress` or any other plain WP core library and a custom boot loader

## Others
* [ ] Update documentation: use https://github.com/WordPress/wordpress-develop as core repository. It is identified by a composer.json as `wordpress/wordpress` so we don't need to maintain a fork anymore (which is abandoned anyway) 
* [ ] Update documentation: focus on setup and use cases, less noise (API reference is basically useless)
* [x] Remove inline comments that don't add any value
* [x] Set Namespace to `Inpsyde\WpTestsStarter` and move everything to `src/`
